mysql:
  image: mysql
  volumes:
    - ./db/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: pursed

app:
  build: src/
  volumes:
    - ./src:/opt/app
  working_dir: /opt/app/django_pursed/
  links:
    - mysql:mysql
  ports:
    - 3000:3000
  environment:
    DATABASE_URL: mysql://root:root@mysql/pursed
